-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  ◈ ENVIRONMENT VARIABLES (AUTOGENERATED)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("NIXOS_OZONE_WL", "1")
hl.env("XDG_PICTURES_DIR", "/home/boni/Pictures")
hl.env("XDG_VIDEOS_DIR", "/data/Videos")
hl.env("WALLPAPER_DIR", "/home/boni/Pictures/Wallpapers")
hl.env("SCRIPT_DIR", "/home/boni/.config/hypr/scripts")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-- Hardware Injections

