-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  ◈ KEYBINDINGS (Auto-generated by Quickshell Settings Watcher)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- ═══════════════════════════════════════════════════════════
-- PORUSZANIE SIĘ MIĘDZY OKNAMI (Meta + Strzałki)
-- ═══════════════════════════════════════════════════════════
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

-- ═══════════════════════════════════════════════════════════
-- PODSTAWOWE APLIKACJE
-- ═══════════════════════════════════════════════════════════
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
-- TODO: manual review — top-level key ';bind = $mainMod, M, exec, logout-with-session' has no enclosing section
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + C", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("chromium"))
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd("librewolf"))
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("spotify-launcher"))
hl.bind(mainMod .. " + I", hl.dsp.exec_cmd("code"))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("elisa"))
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd("lutris"))

-- ═══════════════════════════════════════════════════════════
-- PRZESUWANIE OKIEN (Meta + Shift + Strzałki) - inteligentne
-- Przenosi wewnątrz monitora, lub na inny monitor gdy okno jest na krawędzi
-- ═══════════════════════════════════════════════════════════
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "d" }))

-- ═══════════════════════════════════════════════════════════
-- RESIZE OKIEN (Meta + Ctrl + Strzałki)
-- ═══════════════════════════════════════════════════════════
hl.bind(mainMod .. " + CTRL + left", hl.dsp.window.resize({ x = -40, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CTRL + right", hl.dsp.window.resize({ x = 40, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + CTRL + up", hl.dsp.window.resize({ x = 0, y = -40, relative = true }), { repeating = true })
-- TODO: manual review on line 43 — resizeactive: could not parse pixel coords "0 40q"
-- hl.bind(mainMod .. " + CTRL + down", hl.dsp.resizeactive("0 40q"), { repeating = true })
-- ───────── Mouse & Gestures ─────────
hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

-- ───────── Dynamic Keybinds ─────────
-- ═══════════════════════════════════════════════════════════
-- SCROLL PRZEZ WORKSPACES (Meta + Scroll)
-- ═══════════════════════════════════════════════════════════
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- ═══════════════════════════════════════════════════════════
-- MULTI-MONITOR (Meta + Alt + Strzałki lewo/prawo)
-- ═══════════════════════════════════════════════════════════
hl.bind(mainMod .. " + ALT + left", hl.dsp.focus({ monitor = "l" }))
hl.bind(mainMod .. " + ALT + right", hl.dsp.focus({ monitor = "r" }))
-- ═══════════════════════════════════════════════════════════
-- MYSZ - PRZESUWANIE I RESIZE (Meta + LMB/RMB)
-- ═══════════════════════════════════════════════════════════
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())
-- TODO: manual review — top-level key ';bindm = $mainMod, mouse:272, movewindow' has no enclosing section
-- TODO: manual review — top-level key ';bindm = $mainMod, mouse:273, resizewindow' has no enclosing section
-- TODO: manual review — top-level key ';bind = ALT, F4, exec, hyprctl dispatch killactive' has no enclosing section
-- TODO: manual review — top-level key ';bind = $mainMod&SHIFT_L, F, exec, hyprctl dispatch togglefloating' has no enclosing section
-- TODO: manual review — top-level key ';binde = $mainMod&SHIFT_L, left, resizeactive, -50 0' has no enclosing section
-- TODO: manual review — top-level key ';binde = $mainMod&SHIFT_L, right, resizeactive, 50 0' has no enclosing section
-- TODO: manual review — top-level key ';binde = $mainMod&SHIFT_L, up, resizeactive, 0 -50' has no enclosing section
-- TODO: manual review — top-level key ';binde = $mainMod&SHIFT_L, down, resizeactive, 0 50' has no enclosing section
-- TODO: manual review — top-level key ';bind = $mainMod&CTRL, left, movewindow, l' has no enclosing section
-- TODO: manual review — top-level key ';bind = $mainMod&CTRL, right, movewindow, r' has no enclosing section
-- TODO: manual review — top-level key ';bind = $mainMod&CTRL, up, movewindow, u' has no enclosing section
-- TODO: manual review — top-level key ';bind = $mainMod&CTRL, down, movewindow, d' has no enclosing section
-- TODO: manual review — top-level key ';bind = $mainMod, left, movefocus, l' has no enclosing section
-- TODO: manual review — top-level key ';bind = $mainMod, right, movefocus, r' has no enclosing section
-- TODO: manual review — top-level key ';bind = $mainMod, up, movefocus, u' has no enclosing section
-- TODO: manual review — top-level key ';bind = $mainMod, down, movefocus, d' has no enclosing section
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd("$terminal"))
-- TODO: manual review — top-level key '; bind = $mainMod, F, exec, firefox' has no enclosing section
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("dolphin"))
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("logout-with-session"))
-- TODO: manual review — top-level key '; bind = $mainMod, R, exec, bash ~/.config/hypr/scripts/reload.sh' has no enclosing section
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh toggle clipboard"))
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh toggle movies"))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/qs_manager.sh toggle applauncher"))
hl.bind(mainMod .. " + CTRL + S", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/qs_manager.sh toggle settings"))
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/qs_manager.sh toggle music"))
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/qs_manager.sh toggle battery"))
hl.bind(mainMod .. " + CTRL + W", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/qs_manager.sh toggle wallpaper"))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/qs_manager.sh toggle calendar"))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/qs_manager.sh toggle network"))
hl.bind("$mainMod&SHIFT_L + T", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/qs_manager.sh toggle focustime"))
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/qs_manager.sh toggle volume"))
hl.bind(mainMod .. " + H", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/qs_manager.sh toggle guide"))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/qs_manager.sh toggle monitors"))
hl.bind("Caps_Lock", hl.dsp.exec_cmd("sleep 0.1 && swayosd-client --caps-lock"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("swayosd-client --brightness lower"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("swayosd-client --brightness raise"), { locked = true })
-- ═══════════════════════════════════════════════════════════
-- SCREENSHOTY
-- ═══════════════════════════════════════════════════════════
hl.bind("Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | wl-copy && notify-send \"Screenshot copied to clipboard\""))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("grim ~/Pictures/Screenshots/screenshot-$(date +%Y%m%d-%H%M%S).png && notify-send \"Screenshot saved\""))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | wl-copy && notify-send \"Screenshot copied to clipboard\""))

-- TODO: manual review — top-level key ';bindl = , Print, exec, ~/.config/hypr/scripts/screenshot.sh' has no enclosing section
-- TODO: manual review — top-level key ';bindl = SHIFT_L, Print, exec, ~/.config/hypr/scripts/screenshot.sh --edit' has no enclosing section
-- TODO: manual review — top-level key ';bindl = SUPER, Print, exec, ~/.config/hypr/scripts/screenshot.sh --full' has no enclosing section
-- TODO: manual review — top-level key ';bindl = SUPER SHIFT_L, Print, exec, ~/.config/hypr/scripts/screenshot.sh --full --edit' has no enclosing section
hl.bind("XF86PowerOff", hl.dsp.exec_cmd("bash /home/boni/.local/share/quickshell-lockscreen/lock.sh"), { locked = true })
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("bash /home/boni/.local/share/quickshell-lockscreen/lock.sh"), { locked = true, repeating = true })
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("xf86AudioMicMute", hl.dsp.exec_cmd("swayosd-client --input-volume mute-toggle"), { locked = true })
hl.bind("xf86audiomute", hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"), { locked = true })
hl.bind("xf86audiolowervolume", hl.dsp.exec_cmd("swayosd-client --output-volume -2"), { locked = true, repeating = true })
hl.bind("xf86audioraisevolume", hl.dsp.exec_cmd("swayosd-client --output-volume +2"), { locked = true, repeating = true })
hl.bind(mainMod .. " + 1", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 1"))
hl.bind(mainMod .. " + 2", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 2"))
hl.bind(mainMod .. " + 3", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 3"))
hl.bind(mainMod .. " + 4", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 4"))
hl.bind(mainMod .. " + 5", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 5"))
hl.bind(mainMod .. " + 6", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 6"))
hl.bind(mainMod .. " + 7", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 7"))
hl.bind(mainMod .. " + 8", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 8"))
hl.bind(mainMod .. " + 9", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 9"))
hl.bind(mainMod .. " + 0", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 10"))
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 1 move"))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 2 move"))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 3 move"))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 4 move"))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 5 move"))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 6 move"))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 7 move"))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 8 move"))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 9 move"))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.exec_cmd("~/.config/hypr/scripts/qs_manager.sh 10 move"))
hl.bind(mainMod .. " + TAB", hl.dsp.exec_cmd("~/.config/hypr/scripts/focus_next_monitor.sh"))
hl.bind(mainMod .. " + period", hl.dsp.exec_cmd("rofimoji"))
