-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  ◈ CORE VARIABLES
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mainMod = "SUPER"
local terminal = "kitty"

-- GPU Configuration - Wymuś użycie RX 6700 XT (card1)
-- Wyłącza iGPU Raphael (card0) który powodował crashe w Aquamarine
hl.env("WLR_DRM_DEVICES", "/dev/dri/card1:/dev/dri/card0")
hl.env("AQ_DRM_DEVICES", "/dev/dri/card1")

-- Opcjonalne - fallback dla starszych aplikacji
-- WYŁĄCZONE - masz tylko jedną GPU (card0), DRI_PRIME=1 powodował crashe
-- env = DRI_PRIME,1
hl.env("DRI_PRIME", "0")
