foreground              #e9e0e7
background              #221e24
selection_foreground    #efdcf5
selection_background    #4f4255

cursor                  #e0b8f6
cursor_text_color       #422356

url_color               #f4b7b9

active_border_color     #e0b8f6
inactive_border_color   #4b454d
bell_border_color       #ffb4ab

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #f4d9ff
active_tab_background   #5a396e
inactive_tab_foreground #cdc3ce
inactive_tab_background #221e24
tab_bar_background      #161217

mark1_foreground #422356
mark1_background #e0b8f6
mark2_foreground #382c3e
mark2_background #d3c1d8
mark3_foreground #4c2527
mark3_background #f4b7b9

color0 #4b454d
color8 #978e98

color1 #ffb4ab
color9 #93000a

color2  #e0b8f6
color10 #f4d9ff

color3  #f4b7b9
color11 #ffdada

color4  #d3c1d8
color12 #efdcf5

color5  #5a396e
color13 #735187

color6  #4f4255
color14 #663b3d

color7  #cdc3ce
color15 #e9e0e7
