# Hyprpaper Configuration

# Preload tapety (zmień ścieżkę na swoją tapetę!)
preload = /home/boni/.config/hypr/wallpaper.jpg

# Ustaw tapetę dla każdego monitora
wallpaper = HDMI-A-1,/home/boni/.config/hypr/wallpaper.jpg
wallpaper = DP-3,/home/boni/.config/hypr/wallpaper.jpg

# Splash text
splash = false

# IPC
ipc = on
