-- --------------------------------------------------------------------------------------
--
--   ██╗██╗  ██╗   ██╗ █████╗ ███╗   ███╗██╗██████╗  ██████╗ 
--   ██║██║  ╚██╗ ██╔╝██╔══██╗████╗ ████║██║██╔══██╗██╔═══██╗
--   ██║██║   ╚████╔╝ ███████║██╔████╔██║██║██████╔╝██║   ██║
--   ██║██║    ╚██╔╝  ██╔══██║██║╚██╔╝██║██║██╔══██╗██║   ██║
--   ██║███████╗██║   ██║  ██║██║ ╚═╝ ██║██║██║  ██║╚██████╔╝
--   ╚═╝╚══════╝╚═╝   ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝╚═╝  ╚═╝ ╚═════╝ 
--
--   Created by ilyamiro
--   https://github.com/ilyamiro/nixos-configuration
--
-- --------------------------------------------------------------------------------------

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("colors")

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  ◈ MODULAR CONFIGURATION
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

hl.define_submap("passthru", function()
    -- Dummy bind to force Hyprland to register the submap in memory.
    -- Since you will never press this, all normal keystrokes fall through to Quickshell
    hl.bind("SUPER + SHIFT + CTRL + ALT + F35", hl.dsp.exec_cmd(true))
end)

-- --------------

-- Source: ~/.config/hypr/config/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.monitors")
-- Source: ~/.config/hypr/config/env.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.env")
-- Source: ~/.config/hypr/config/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.autostart")
-- Source: ~/.config/hypr/config/variables.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.variables")
-- Source: ~/.config/hypr/config/settings.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.settings")
-- Source: ~/.config/hypr/config/rules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.rules")
-- Source: ~/.config/hypr/config/keybindings.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.keybindings")

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-3",
    default = true,
})

hl.workspace_rule({
    workspace = "2",
    monitor = "DP-3",
})

hl.workspace_rule({
    workspace = "3",
    monitor = "DP-3",
})

hl.workspace_rule({
    workspace = "4",
    monitor = "DP-3",
})

hl.workspace_rule({
    workspace = "5",
    monitor = "DP-3",
})

hl.workspace_rule({
    workspace = "6",
    monitor = "HDMI-A-1",
    default = true,
})

hl.workspace_rule({
    workspace = "7",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "8",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "9",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "10",
    monitor = "HDMI-A-1",
})

-- TODO: manual review — top-level key 'focus_on_activate = false' has no enclosing section

hl.config({
    cursor = {
        no_hardware_cursors = false, -- false = używaj hardware cursor (mniej obciąża GPU)
        no_break_fs_vrr = true, -- WYŁĄCZONE VRR w fullscreen - stabilność
        min_refresh_rate = 60, -- Minimalny refresh rate (oszczędza GPU gdy idle)
        hotspot_padding = 0, -- Bez paddingu = mniej GPU work
        inactive_timeout = 0, -- 0 = cursor zawsze aktywny (bez ukrywania)
        no_warps = false, -- false = pozwól na warping (lepsze dla multi-monitor)
        persistent_warps = false, -- false = nie zapamiętuj warp positions
        warp_on_change_workspace = false, -- false = nie warp przy zmianie workspace
    },
})

