# --------------------------------------------------------------------------------------
#
#   ██╗██╗  ██╗   ██╗ █████╗ ███╗   ███╗██╗██████╗  ██████╗ 
#   ██║██║  ╚██╗ ██╔╝██╔══██╗████╗ ████║██║██╔══██╗██╔═══██╗
#   ██║██║   ╚████╔╝ ███████║██╔████╔██║██║██████╔╝██║   ██║
#   ██║██║    ╚██╔╝  ██╔══██║██║╚██╔╝██║██║██╔══██╗██║   ██║
#   ██║███████╗██║   ██║  ██║██║ ╚═╝ ██║██║██║  ██║╚██████╔╝
#   ╚═╝╚══════╝╚═╝   ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝╚═╝  ╚═╝ ╚═════╝ 
#
#   Created by ilyamiro
#   https://github.com/ilyamiro/nixos-configuration
#
# --------------------------------------------------------------------------------------

source = ~/.config/hypr/colors.conf

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ MODULAR CONFIGURATION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

submap = passthru
# Dummy bind to force Hyprland to register the submap in memory.
# Since you will never press this, all normal keystrokes fall through to Quickshell
bind = SUPER SHIFT CTRL ALT, F35, exec, true
submap = reset

# --------------

source = ~/.config/hypr/config/monitors.conf
source = ~/.config/hypr/config/env.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/variables.conf
source = ~/.config/hypr/config/settings.conf
source = ~/.config/hypr/config/rules.conf
source = ~/.config/hypr/config/keybindings.conf



workspace=1,monitor:DP-3,default:true
workspace=2,monitor:DP-3
workspace=3,monitor:DP-3
workspace=4,monitor:DP-3
workspace=5,monitor:DP-3
workspace=6,monitor:HDMI-A-1,default:true
workspace=7,monitor:HDMI-A-1
workspace=8,monitor:HDMI-A-1
workspace=9,monitor:HDMI-A-1
workspace=10,monitor:HDMI-A-1


focus_on_activate = false  # Focus okna gdy się aktywuje

cursor {
    no_hardware_cursors = false  # false = używaj hardware cursor (mniej obciąża GPU)
    no_break_fs_vrr = true  # WYŁĄCZONE VRR w fullscreen - stabilność
    min_refresh_rate = 60  # Minimalny refresh rate (oszczędza GPU gdy idle)
    hotspot_padding = 0  # Bez paddingu = mniej GPU work
    inactive_timeout = 0  # 0 = cursor zawsze aktywny (bez ukrywania)
    no_warps = false  # false = pozwól na warping (lepsze dla multi-monitor)
    persistent_warps = false  # false = nie zapamiętuj warp positions
    warp_on_change_workspace = false  # false = nie warp przy zmianie workspace
}